default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: NelsonParksProject_development

test:
  <<: *default
  database: NelsonParksProject_test

production:
  <<: *default
  database: NelsonParksProject_production
  username: NelsonParksProject
  password: <%= ENV["NELSONPARKSPROJECT_DATABASE_PASSWORD"] %>
